services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ecommerce
    volumes:
      - /home/efesengul/projects/docker_mysql:/var/lib/mysql
    ports:
      - 3306:3306
  pma:
    image: phpmyadmin:latest
    environment:
    - MYSQL_ROOT_PASSWORD=123
    - PMA_HOST=db
    - PMA_ARBITRARY=1
    ports:
      - 8080:80